(()=>{'use strict';const $=id=>document.getElementById(id);const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};const assets=[
{id:'deep-sea-engineer',name:'深海工程师',type:'角色 · 科幻探索',use:'Teams 美国游戏方向。以明确的职业角色带出同项目载具，服务共享资产工作方式。',shape:'全身轮廓、承重双腿与背包层次；盔甲弧面和肩部软硬转折让身体有可读体积。',material:'象牙色硬壳、深色织物、铜色连接件与橡胶软管分别表现光泽与粗糙度。',limit:'只有单张二维概念。手部、装备连接和背面结构未通过真实网格、绑定或游戏引擎验证。'},
{id:'tidal-research-station',name:'潮汐研究站',type:'环境模块 · 海岸探险',use:'Teams 欧洲游戏项目方向。孤立的建筑模块与平台轮廓，说明同一探险项目的环境资产用途。',shape:'双塔、玻璃连桥与岩石基座分出前后空间；拱洞、楼梯和完整底座帮助读懂尺度。',material:'浅色石材、铜绿穹顶、玻璃与深灰岩层的响应不同，不靠霓虹光效假装质感。',limit:'不是完整生成游戏世界，也不是客户案例；模块拼接、背面、真实贴图和可玩空间未验证。'},
{id:'mountain-packbeast',name:'矿岩驮兽',type:'生物 · 探险坐骑',use:'供游戏美术负责人选型的备选英雄资产。独特矿角、背甲和驮鞍比常规人物更有识别性。',shape:'宽肩、四足承重、完整尾巴与分叉矿角形成强轮廓；底座与接触阴影交代重量。',material:'石质装甲、柔性皮肤、棕色皮革与铜扣形成材质对比。',limit:'角尖和尾部靠近原图边缘，本页完整保留。它不是下方真实FBX坐骑的输入或输出，不能拼成前后对照。'},
{id:'deepsea-surveyor',name:'深海勘测潜航器',type:'机械载具 · 硬表面',use:'API 美国游戏与资产工具方向。独立载具比普通场景照更适合解释一项生成任务与开发工具关系。',shape:'四个环形推进器、前端镜头与橙色采样臂；负空间、曲面与前后遮挡给出深度。',material:'陶瓷外壳、铜色环、石墨结构和镜头玻璃有可区分的高光与粗糙度。',limit:'环与机械臂较靠近原图边缘，排版不裁边。不证明实际机械结构、物理模拟或本次API任务成功。'},
{id:'espresso-machine',name:'双头意式咖啡机',type:'产品 · 企业内容',use:'API 欧洲企业内容方向。用独立产品对象说明商品内容工具的应用，而不是拿椅子或场景照泛指所有业务。',shape:'完整双头机身、控制区域、托盘与脚座，侧面厚度清楚；不把单视角当成数字孪生。',material:'翡翠绿搪瓷、拉丝钢板与胡桃木把手，用不同反射强弱和表面细节分开。',limit:'GPT二维产品概念，不是实拍商品、精确尺寸复刻或已实现的3D查看器。'}];
const ads=[
{id:'T19-US',title:'One crew. One asset library.',audience:'Teams · 美国游戏工作流',primary:'Keep your game’s characters and vehicles in one shared workspace with Tripo Studio Team Plan. Find, share and reuse assets.',headline:'A shared library for your game team',note:'共享资产是基本能力；画面中的工程师与潜航器是人为选择的项目概念，不代表自动风格一致或实时共编。'},
{id:'T19-EU',title:'A world to build. A place to share.',audience:'Teams · 欧洲游戏项目用途',primary:'Keep the assets for your coastal adventure project together in a shared workspace with Tripo Studio Team Plan.',headline:'Your game project’s assets, together',note:'环境模块展示项目用途，而非真实客户游戏、完整场景生成或已在引擎验证的资产。'},
{id:'A19-US',title:'Your tools. A deeper dimension.',audience:'API · 美国游戏与3D资产工具',primary:'Build Tripo API into your game tools. Submit a task, track its status and retrieve the result after success. Then review and refine.',headline:'3D generation inside your asset workflow',note:'提交、查询与成功后取回是异步流程示意，集成仍需工程工作。潜航器不是本次API输出。'},
{id:'A19-EU',title:'Give your products another dimension.',audience:'API · 欧洲企业产品内容',primary:'Add Tripo API to your product-content tools. Retrieve results after successful tasks, then review each model for your product experience.',headline:'3D generation for product-content tools',note:'产品内容是应用方向，不代表已部署客户系统、精确数字孪生或API自带查看器。'}];
let opener=null,timer;function openImage(src,name,note,button){opener=button;$('lightbox-image').src=src;$('lightbox-image').alt=name;$('model-lightbox-title').textContent=name;$('lightbox-note').textContent=note;$('lightbox-original').href=src;$('model-lightbox').showModal();$('close-lightbox').focus();}function img(src,alt){const n=el('img');n.src=src;n.alt=alt;n.width=1254;n.height=1254;n.loading='lazy';n.addEventListener('error',()=>{const p=el('p','图片暂未载入，请使用原图链接检查；不以其他素材替代。');n.replaceWith(p);});return n;}
assets.forEach(a=>{const card=el('article',null,'model-card');card.id=a.id;const source=`assets/v19/concepts/${a.id}.png`;const button=el('button',null,'model-image-button');button.type='button';button.setAttribute('aria-label',`放大${a.name}原图`);button.append(img(source,`${a.name}，GPT二维概念图，非Tripo模型结果`));button.addEventListener('click',()=>openImage(source,a.name,a.limit,button));const dl=el('dl');for(const [key,label]of[['use','适用方向'],['shape','体积与轮廓看点'],['material','材质看点']])dl.append(el('dt',label),el('dd',a[key]));const link=el('a','打开完整原图 ↗');link.href=source;link.target='_blank';link.rel='noopener';card.append(button,el('p',`${a.type} · GPT 二维原创概念`,'model-tag'),el('h3',a.name),dl,el('p',a.limit,'boundary'),link);$('model-gallery').append(card);});
ads.forEach(a=>{const card=el('article',null,'model-ad-card');card.id=a.id;const source=`assets/v19/${a.id}.png`;const original=el('a');original.href=source;original.target='_blank';original.rel='noopener';original.append(img(source,`${a.id} ${a.title}，AI概念静态广告`));const links=el('div',null,'model-ad-links');const download=el('a','下载 PNG');download.href=source;download.download=`${a.id}.png`;const copy=el('button','复制图文文案');copy.type='button';copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText([a.primary,a.headline,'Learn more'].join('\n\n'));$('model-copy-status').textContent='已复制图文文案。未投放、未发送。';}catch{$('model-copy-status').textContent='复制不可用，请直接选中下方英文文案。';}clearTimeout(timer);timer=setTimeout(()=>$('model-copy-status').textContent='',5000);});links.append(download,copy);const details=el('details');details.append(el('summary','文案与证据边界'),el('p',`Headline: ${a.headline}`),el('p','Feed CTA: Learn more'),el('p',a.note),el('p',`Primary ${a.primary.length} 字符 · Headline ${a.headline.length} 字符`,'lengths'));card.append(original,el('p',a.audience,'model-tag'),el('h3',a.title),el('p',a.primary,'post-copy'),links,details);$('v19-ad-gallery').append(card);});
const initialHash=location.hash;document.fonts.ready.then(()=>{if(initialHash&&location.hash===initialHash)document.getElementById(initialHash.slice(1))?.scrollIntoView({block:'start',behavior:'instant'});});
$('close-lightbox').addEventListener('click',()=>$('model-lightbox').close());$('model-lightbox').addEventListener('close',()=>opener?.focus());$('model-lightbox').addEventListener('click',e=>{if(e.target===$('model-lightbox')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});})();
